api:
  port: 9000
  basicAuth:
    name: admin
    password: public

db:
  type: sqlite
  sqlite:
    filePath: iothub.sqlite
    showSql: true
  mysql:
    host: 127.0.0.1
    port: 3306
    user: iothub
    password: public
    db: iothub
    charset: utf8
    timezone: Asia%2FShanghai
    maxIdleConns: 4
    maxOpenConns: 50
    connMaxLifetime: 60
    showSql: true

connector:
  type: embed
  mqttClient:
    clientId: $iothub
    host: localhost
    port: 1883
    user: $iothub
    password: public
    cleanSession: false
  mqttBroker:
    tcpPort: 1883
    wsPort: 8083
    superUsers:
      - name: $iothub
        password: public
      - name: $biz
        password: public
  emqx:
    apiPrefix: http://localhost:18083
    apiUser: admin
    apiPassword: public

log:
  level: debug
